---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
    customize:
      cpus: 2
      memory: 1024
    network:
      - ["private_network", {ip: "11.12.14.11"}]
  run_list:
  - recipe[apt]
suites:
- name: default
  run_list:
    - recipe[nvm_test::default]
    - recipe[minitest-handler]
- name: nvm-install
  run_list:
    - recipe[nvm_test::nvm_install]
    - recipe[minitest-handler]
- name: nvm-alias-default
  run_list:
    - recipe[nvm_test::nvm_alias_default]
    - recipe[minitest-handler]
- name: nvm-install-from-source
  run_list:
    - recipe[nvm_test::nvm_install_from_source]
    - recipe[minitest-handler]